[server]
enableStaticServing = true

[theme]
base = "dark"

# Primary accent color for interactive elements.
primaryColor = "#5c74a8"

# Background color for the main content area.
backgroundColor = "#1f273b"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#586594"

# Color used for almost all text.
textColor = "#EDEEEF"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
font = "sans serif"